site_name: SAI Community
site_author: SAI
site_description: >-
  SAI Community

site_url: https://sjtu-sai.github.io/SAI-Community/
repo_name: SAI Community
repo_url: https://github.com/SJTU-SAI/SAI-Community

theme:
  custom_dir: overrides
  name: material
  language: zh
  favicon: assets/sai.jpg
  static_templates:
    - 404.html
  include_search_page: true
  palette:
    scheme: sai
    primary: teal
    accent: teal
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  font:
    text: Roboto Slab
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    annotation: material/arrow-right-circle
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
      linenums: true
      auto_title: true
      line_spans: __span
      pygments_lang_class: true
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

nav:
  - Hello World: "index.md"
  - About: "about.md"
  - Roadmaps:
    - README: "roadmaps/init.md"
    - Website: "roadmaps/website-recommend.md"
  - Tools:
    - 命令行入门: "tools/cli.md"
    - Python 项目管理: "tools/python-package-managing.md"
  - Courses:
    - README: "courses/init.md"
    - Semester 1.1:
      - 人工智能导论: "courses/Semester1.1/SJTU-AI1801.md"
      - 线性代数: "courses/Semester1.1/SJTU-MATH1205H.md"
      - 数学分析I: "courses/Semester1.1/SJTU-MATH1607H.md"
      - 程序设计基础: "courses/Semester1.1/SJTU-AI1802.md"
    - Semester 1.2:
      - 数学分析II: "courses/Semester1.2/SJTU-MATH1608H.md"
      - 大学物理I: "courses/Semester1.2/SJTU-PHY1251H.md"
      - 数据结构: "courses/Semester1.2/SJTU-CS0501H.md"
      - 离散数学: "courses/Semester1.2/SJTU-CS2501H.md"
      - 编程综合实践: "courses/Semester1.2/SJTU-AI1803.md"
  - Contributions:
      - Contributions: "contributions/hello_world.md"
      - Contributors: "contributions/contributors.md"
      - Tutorials:
        - Advanced Markdown: "contributions/markdown_tutorial.md"
        - Local Launch: "contributions/local_run.md"
        - Demo: "templates/template.md"
        - Pull Request Tutorial: "contributions/Pull_Request_Tutorial.md"

plugins:
  - glightbox

exclude_docs: |
  !.*
  !templates

